package za.co.smartcall.smartload.hibernate;

// Generated 17 Feb 2015 10:03:49 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

/**
 * Network generated by hbm2java
 */
@Entity
@Table(name = "NETWORK")
public class Network implements java.io.Serializable {

	private int id;
	private String network;


	public Network() {
	}

	public Network(int id, String network) {
		this.id = id;
		this.network = network;
	}


	
	public Network(za.co.smartcall._2010._12.common.Network network) {
		this.id = (int)network.getId();
		this.network = network.getDescription();
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NETWORK", nullable = false, length = 50)
	public String getNetwork() {
		return this.network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	
	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this);
	}
	
}
