package za.co.smartcall.smartload.hibernate;

// Generated 16 Feb 2015 12:49:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionStatus generated by hbm2java
 */
@Entity
@Table(name = "SUBMISSION_STATUS")
public class SubmissionStatus implements java.io.Serializable {

	private int id;
	private String subStatus;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public SubmissionStatus() {
	}

	public SubmissionStatus(int id, String subStatus) {
		this.id = id;
		this.subStatus = subStatus;
	}

	public SubmissionStatus(int id, String subStatus,
			Set<Transaction> transactions) {
		this.id = id;
		this.subStatus = subStatus;
		this.transactions = transactions;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "SUB_STATUS", nullable = false, length = 50)
	public String getSubStatus() {
		return this.subStatus;
	}

	public void setSubStatus(String subStatus) {
		this.subStatus = subStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "submissionStatus")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
