package za.co.smartcall.smartload.hibernate;

// Generated 16 Feb 2015 12:49:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Voucher generated by hbm2java
 */
@Entity
@Table(name = "VOUCHER")
public class Voucher implements java.io.Serializable {

	private int id;
	private File file;
	private String boxnumber;
	private String description;
	private String expirydate;
	private String voucherId;
	private String pinNumber;

	public Voucher() {
	}

	public Voucher(int id, File file, String boxnumber, String description,
			String expirydate, String voucherId, String pinNumber) {
		this.id = id;
		this.file = file;
		this.boxnumber = boxnumber;
		this.description = description;
		this.expirydate = expirydate;
		this.voucherId = voucherId;
		this.pinNumber = pinNumber;
	}
	
	public Voucher(String[] contentArray,File pFile){
		voucherId = contentArray[0];
		boxnumber = contentArray[1];
		pinNumber =contentArray[2];
		expirydate=contentArray[3];
		description=contentArray[4];
		file = pFile;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILE", nullable = false)
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "BOXNUMBER", nullable = false, length = 50)
	public String getBoxnumber() {
		return this.boxnumber;
	}

	public void setBoxnumber(String boxnumber) {
		this.boxnumber = boxnumber;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRYDATE", nullable = false, length = 23)
	public String getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(String expirydate) {
		this.expirydate = expirydate;
	}

	@Column(name = "VOUCHER_ID", nullable = false, length = 50)
	public String getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(String voucherId) {
		this.voucherId = voucherId;
	}

	@Column(name = "PIN_NUMBER", nullable = false, length = 50)
	public String getPinNumber() {
		return this.pinNumber;
	}

	public void setPinNumber(String pinNumber) {
		this.pinNumber = pinNumber;
	}
	
	

}
